"""
This module contains the base plotting functions.

If [`Makie`](https://makie.org) is not installed, none of the plotting functions will work.
If a Makie backend is installed and importend, concrete methods will be added to these functions by the MakieMCMRSimulator extension.
This makes Makie an optional dependency of MCMRSimulator, which will only be required if you want to use the MCMRSimulator plotting capabilities.

In addition to these empty plotting functions, this module defines the [`PlotPlane`](@ref) for any 2D-projections and helper functions to project onto this plane.
"""
module Plot
import CoordinateTransformations
import LinearAlgebra: cross, ⋅, norm
import StaticArrays: SVector, MVector
import ...Spins: Snapshot, orientation, SpinOrientation, position
import ...Methods: get_rotation
import ...Geometries.Internal: ray_grid_intersections, FixedGeometry, FixedObstructionGroup, Wall, Cylinder, Sphere, obstructions, Shift
import ...Geometries.User: ObstructionGroup, fix
import ...SequenceParts: SequenceWaveform, SequenceEvent, GradientEvent, PulseEvent


const GeometryLike = Union{FixedGeometry, FixedObstructionGroup, ObstructionGroup, Vector{<:ObstructionGroup}}
const Projectable = Union{GeometryLike, Snapshot, Vector{<:Snapshot}}


"""
    plot([plot_plane,] geometry; kwargs...)
    plot!([scene,] [plot_plane,] geometry; kwargs...)
    plot_geometry([plot_plane,] geometry; kwargs...)
    plot_geometry!([scene,] [plot_plane,] geometry; kwargs...)

Plots a given geometry.
If a [`PlotPlane`](@ref) is provided the 2D projection of the geometry onto this plane is plotted.
Otherwise, the geometry is plotted in 3D.

If you want to overlay the off-resonance field, call [`plot_off_resonance`](@ref) first before calling this function.

This function will only work if a [`Makie`](https://makie.org) backend is imported.
"""
function plot_geometry end
function plot_geometry! end

"""
    plot([plot_plane], snapshot; kind=:scatter, kwargs...)
    plot!([scene,] [plot_plane], snapshot; kind=:scatter, kwargs...)
    plot_snapshot([plot_plane], snapshot; kind=:scatter, kwargs...)
    plot_snapshot!([scene,] [plot_plane], snapshot; kind=:scatter, kwargs...)

Plots a [`Snapshot`](@ref) in a new plot.

The spins are plotted in 2D projected onto the [`PlotPlane`](@ref) if one is provided.
Otherwise, the spins are plotted in 3D (does not work for `kind=:image`).

There are three kinds of snapshot plots available:
## Scatter plot
Default (or set using `kind=:scatter`). Each spin is plotted as a point with the colour set by the transverse magnetisation.
Additional keywords are passed on to `Makie.scatter` (namely, `marker`, `markersize`, `strokecolor`, `strokewidth`, `glowcolor`, `glowwidth`).

## Dyad plot
Set using `kind=:dyad`. Each spin is plotted as a dyad. For a 2D dyad the orientation is set by the transverse magnetisation.
For a 3D dyad the full magnetisation is used to set the orientation.
Additional keywords are passed on to `Makie.arrows` (namely, `arrowsize`, `arrowhead`, `arrowtail`, `linestyle`, `lengthscale`, `quality`, `markerspace`, `diffuse`, `specular`, `shininess`).

## Image
Set using `kind=:image`. The average magnetisation is plotted across the [`PlotPlane`](@ref).
The colour in each pixel is set by the average transverse magnetisation of the local spins.
Set `interpolate=false` to disable interpolating the colors.
This plot will not work in 3D (i.e., a [`PlotPlane`](@ref) is required).

This function will only work if a [`Makie`](https://makie.org) backend is imported.
"""
function plot_snapshot end
function plot_snapshot! end

"""
    plot_off_resonance(plot_plane, geometry; kwargs...)
    plot_off_resonance!([scene,] plot_plane, geometry; kwargs...)

Plots the off-resonance field generated by a given geometry within the [`PlotPlane`](@ref).

This function will only work if a [`Makie`](https://makie.org) backend is imported.
"""
function plot_off_resonance end
function plot_off_resonance! end

"""
    plot([plot_plane], snapshots; kwargs...)
    plot!([scene,] [plot_plane], snapshots; kwargs...)
    plot_trajectory([plot_plane], snapshots; kwargs...)
    plot_trajectory!([scene,] [plot_plane], snapshots; kwargs...)

Plots the spin trajectory in a vector of [`Snapshot`](@ref) on an existing plot scene.

The spins are plotted in 2D projected onto the [`PlotPlane`](@ref) if one is provided.
Otherwise, the spins are plotted in 3D.
At each location along the trajectory, the colour is set by the transverse magnetisation.
Additional keywords are passed on to `Makie.lines!`.

This function will only work if a [`Makie`](https://makie.org) backend is imported.
"""
function plot_trajectory end
function plot_trajectory! end

"""
    plot(sequence; kwargs...)
    plot!([scene,] sequence; kwargs...)
    plot_sequence(sequence; kwargs...)
    plot_sequence!([scene,] sequence; kwargs...)

Plots a given sequence in a sequence diagram.

The sequence diagram is a 2D plot with time on the x-axis and the different sequence components on the y-axis.

This function will only work if a [`Makie`](https://makie.org) backend is imported.
"""
function plot_sequence end
function plot_sequence! end



"""
    simulator_movie(filename, simulation, times, size; resolution=(1600, 800), trajectory_init=30, signal_init=10000, framerate=50, plane_orientation=:z, kwargs...)

Writes a movie of the [`Simulation`](@ref MCMRSimulator.Simulations.Simulation) to the given `filename`.

Each frame of the movie shows the [`Snapshot`](@ref MCMRSimulator.Spins.Snapshot) at given `times`.
`size` is a tuple with the size of the plotted region in the x- and y-direction.
If there is a repeating geometry, then it is strongly recommended to use the size of the repeat for `size`.

Keyword arguments:
- `resolution`: pixel resolution of each frame in the movie.
- `trajectory_init`: how many spins to plot on each frame.
- `signal_init`: how many spins to use to evaluate the signal evolution.
- `framerate`: wait time between each subsequent frame in the movie.
- `plane_orientation`: orienation of the plane on which the spins are projected (see [`PlotPlane`](@ref)).

Additional keyword arguments are passed on to [`plot_snapshot`](@ref).

This function will only work if [`Makie`](https://makie.org) is installed and imported.
"""
function simulator_movie end


"""
Defines a finite plane in the 3D space used for plotting.

# Constructor
    PlotPlane(normal=[0, 0, 1], position=[0, 0, 0]; size=10., sizex=<size>, sizey=<size>, ngrid=100)

Arguments:
- `normal`: length-3 vector with the orientation perpendicular to the plane (default to z-direction).
- `position`: position of plane as a length-3 vector (defaults to origin).
- `sizex`: size of the plane in the x-direction (before rotating to `normal`).
- `sizey`: size of the plane in the y-direction (before rotating to `normal`).
- `size`: set default value for `sizex` and `sizey`.
- `ngrid`: number of grid elements to split the plane up into for plotting.
"""
struct PlotPlane
    transformation :: CoordinateTransformations.Transformation
    sizex :: Real
    sizey :: Real
end


function PlotPlane(
    normal=:z, 
    position :: AbstractVector{<:Real}=zero(SVector{3, Float64});
    sizex=nothing, sizey=nothing, size=10.,
)
    if isnothing(sizex)
        sizex = size
    end
    if isnothing(sizey)
        sizey = size
    end
    rotation = get_rotation(normal, 3; reference_dimension=:z)
    position = SVector{3}(position)
    transform = CoordinateTransformations.AffineMap(rotation, position)
    PlotPlane(CoordinateTransformations.inv(transform), sizex, sizey)
end


function project(pp::PlotPlane, pos::SVector{3, Float64})
    base = pp.transformation(pos)
    sizex, sizey = pp.sizex, pp.sizey
    correct = [isfinite(sizex) ? sizex : 0., isfinite(sizey) ? sizey : 0., 0.] / 2.
    mod.(base .+ correct, (sizex, sizey, Inf)) .- correct
end

function project_trajectory(pp::PlotPlane, pos::AbstractVector{<:SVector{3, Float64}})
    transformed = pp.transformation.(pos)
    pos2D = map(p -> SVector{3, Float64}(
        isfinite(pp.sizex) ? p[1] / pp.sizex + 0.5 : 0.5,
        isfinite(pp.sizey) ? p[2] / pp.sizey + 0.5 : 0.5,
        0.5
    ), transformed)
    function to_pos!(time::Float64, position::SVector{3, Float64})
        idx1 = Int(floor(time))
        idx2 = Int(ceil(time))
        if idx1 == idx2
            pos_ref = pos2D[idx1]
        else
            pos_ref = pos2D[idx2] .* (time - idx1) .+ pos2D[idx1] .* (idx2 - time)
        end
        push!(all_pos, SVector{2}(
            isfinite(pp.sizex) ? pp.sizex * (position[1] - 0.5) : pos_ref[1],
            isfinite(pp.sizey) ? pp.sizey * (position[2] - 0.5) : pos_ref[2],
        ))
        push!(times, time)
    end
    empty = SVector{2, Float64}(NaN, NaN)
    all_pos = SVector{2, Float64}[]
    times = Float64[]
    for (pos_index, origin, destination) in zip(1:length(pos2D)-1, pos2D[1:end-1], pos2D[2:end])
        for (_, t1, p1, t2, p2) in  ray_grid_intersections(origin, destination)
            if pos_index == 1 && t1 == zero(t1)
                to_pos!(pos_index + t1, p1)
            end
            if t1 == zero(t1) && t2 == one(t2)
                to_pos!(pos_index + t2, p2)
            elseif t1 == zero(t1)
                to_pos!(pos_index + t2, p2)
                push!(all_pos, empty)
                push!(times, NaN)
            elseif t2 == one(t2)
                to_pos!(pos_index + t1, p1)
                to_pos!(pos_index + t2, p2)
            else
                to_pos!(pos_index + t1, p1)
                to_pos!(pos_index + t2, p2)
                push!(all_pos, empty)
                push!(times, NaN)
            end
        end
    end
    return all_pos, times
end


"""
    project_on_grid(plot_plane, snap, ngrid)

Spins from the [`Snapshot`](@ref) are projected onto the grid defined by [`PlotPlane`](@ref) in two ways:
- along the normal spins are projected onto the plane from infinitely far (TODO: give finite extent)
- in the other directions any spins are projected onto the plane using mod(position[1], `sizex`) and mod(position[2], `sizey`).
    This assumes that the geometry and field repeats itself ad infinitum beyond the `PlotPlane` (TODO: allow this assumption to be turned off).
In effect, this means that all spins are projected onto the `PlotPlane`. The average spin orientation in each grid cell is returned.
"""
function project_on_grid(pp::PlotPlane, snap::Snapshot{1}, ngrid::Int)
    positions = [project(pp, position(spin)) for spin in snap]
    xrange = extrema(v->v[1], positions)
    yrange = extrema(v->v[2], positions)

    res = zeros(MVector{3}, ngrid, ngrid)
    hits = zeros(Int, ngrid, ngrid)
    for (spin, pos) in zip(snap, positions)
        relx = (pos[1] - xrange[1])/(xrange[2] - xrange[1])
        rely = (pos[2] - yrange[1])/(yrange[2] - yrange[1])
        x_index = min.(Int(floor(relx * (ngrid - 1))), ngrid - 2) + 1
        y_index = min.(Int(floor(rely * (ngrid - 1))), ngrid - 2) + 1
        vs = orientation(spin)
        for (xi, yi) in [
            (x_index, y_index),
            (x_index+1, y_index),
            (x_index, y_index+1),
            (x_index+1, y_index+1),
        ]
            res[xi, yi] += vs
            hits[xi, yi] += 1
        end
    end
    (range(xrange..., ngrid), range(yrange..., ngrid), SpinOrientation.(res ./ hits))
end


project_geometry(plot_plane::PlotPlane, geometry::GeometryLike) = project_geometry(plot_plane, fix(geometry))

function project_geometry(plot_plane::PlotPlane, geometry::FixedGeometry)
    projections = []
    for t in geometry
        append!(projections, project_geometry(plot_plane, t))
    end
    projections
end

"""
    project_geometry(plot_plane, transform)

Projects the plane on the intrinsic plane of the obstructions deformed by `transform`.
"""
function project_geometry(plot_plane::PlotPlane, group::FixedObstructionGroup{N}) where {N}
    center_obstruction_space = plot_plane.transformation(zero(SVector{3, Float64}))

    obstruction_coordinates_in_plot_plane = SVector{N, SVector{3, Float64}}(map(p->SVector{3, Float64}(plot_plane.transformation(p)) .- center_obstruction_space, eachcol(group.rotation)))

    projections = []
    for obstruction in obstructions(group)
        base, shift = if obstruction isa Shift
            obstruction.base, obstruction.shift
        else
            obstruction, zero(SVector{N, Float64})
        end

        obstruction_center_in_plot_plane = plot_plane.transformation(group.rotation * shift)
        append!(projections, project_obstruction(base, obstruction_center_in_plot_plane, obstruction_coordinates_in_plot_plane, group.repeats, (plot_plane.sizex, plot_plane.sizey)))
    end
    projections
end


"""
    project_obstruction(obstruction, center, obstruction_coordinates_in_plot_plane, repeats, sizes)

Helper function for `project_geometry` that projects a single obstruction onto the plot plane.
"""
function project_obstruction(wall::Wall, center::SVector{3, Float64}, obstruction_coordinates_in_plot_plane::SVector{1, SVector{3, Float64}}, repeats::Union{Nothing, SVector{1, Float64}}, sizes::Tuple{<:Real, <:Real})
    constant_center = obstruction_coordinates_in_plot_plane[1] ⋅ center
    normal = obstruction_coordinates_in_plot_plane[1][1:2]
    halfs = (sizes[1]/2, sizes[2]/2)

    function get_line(constant::Float64)
        if abs(normal[1]) > abs(normal[2])
            return [
                SVector{2, Float64}((constant + normal[2] * sizes[2]) / normal[1], -sizes[2]),
                SVector{2, Float64}((constant - normal[2] * sizes[2]) / normal[1], sizes[2]),
                SVector{2, Float64}(NaN, NaN),
            ]
        else
            return [
                SVector{2, Float64}(sizes[1], (constant - normal[1] * sizes[1]) / normal[2]),
                SVector{2, Float64}(-sizes[1], (constant + normal[1] * sizes[1]) / normal[2]),
                SVector{2, Float64}(NaN, NaN),
            ]
        end
    end
    if ~isnothing(repeats)
        repeat_constant_shift = repeats[1] * norm(normal)
        closest_center = mod(constant_center, repeat_constant_shift)
        max_size = abs.(normal) ⋅ halfs
        nshift = div(max_size + abs(closest_center), repeat_constant_shift, RoundUp)
    
        line = SVector{2, Float64}[]
        for shift in -nshift:nshift
            append!(line, get_line(shift * repeat_constant_shift + closest_center))
        end
    else
        line = get_line(constant_center)[1:2]
    end
    cut_line(line, halfs)
end

function project_obstruction(obstruction::Cylinder, center_vec::SVector{3, Float64}, obstruction_coordinates_in_plot_plane::SVector{2, SVector{3, Float64}}, repeats::Union{Nothing, SVector{2, Float64}}, sizes::Tuple{<:Real, <:Real})
    (dirx, diry) = obstruction_coordinates_in_plot_plane
    normal = cross(dirx, diry)
    if normal[3] == 0
        error("Can not plot cylinders or spirals perfectly aligned with plotting plane")
    end
    halfs = (sizes[1]/2, sizes[2]/2)
    center = (center_vec .- normal .* (center_vec[3] / normal[3]))[1:2]
    dirx = (dirx .- normal .* (dirx[3] / normal[3]))[1:2]
    diry = (diry .- normal .* (diry[3] / normal[3]))[1:2]

    projection_size = normal[3] * normal[3]

    theta_normal = atan(normal[2], normal[1])
    function relative_radius(theta)
        ct_rot = cos(theta - theta_normal)
        sqrt(1 / (1 - ct_rot * ct_rot * (1 - projection_size)))
    end

    theta = (0:0.02:2) * π
    radius = obstruction.radius .* relative_radius.(theta)

    points = map((r, t) -> SVector{2, Float64}(r .* cos(t), r * sin(t)), radius, theta)
    push!(points, SVector{2, Float64}(NaN, NaN))

    function get_line(center :: SVector{2, Float64})
        map(p->SVector{2, Float64}(p[1] + center[1], p[2] + center[2]), points)
    end

    if ~isnothing(repeats)
        stepx = dirx * repeats[1]
        stepy = diry * repeats[2]

        toshift = round.([stepx stepy] \ center)
        closest_center = center - (toshift[1] * stepx + toshift[2] * stepy)

        outer_radius = isa(obstruction, Cylinder) ? obstruction.radius : obstruction.outer
        nshiftx = div(abs.(dirx) ⋅ (halfs .+ abs.(closest_center)) + projection_size * outer_radius, repeats[1], RoundUp)
        nshifty = div(abs.(diry) ⋅ (halfs .+ abs.(closest_center)) + projection_size * outer_radius, repeats[2], RoundUp)
        line = SVector{2, Float64}[]
        for i in -nshiftx:nshiftx
            int_pos = closest_center .+ i .* stepx
            for j in -nshifty:nshifty
                pos = SVector{2}(int_pos .+ j .* stepy)
                append!(line, get_line(pos))
            end
        end
    else
        line = get_line(SVector{2}(center))
    end
    cut_line(line, halfs)
end

function cut_line(old_line::AbstractVector{SVector{2, Float64}}, sizes)
    _inside(point::SVector{2, Float64}) = abs(point[1]) <= sizes[1] && abs(point[2]) <= sizes[2]
    new_line = SVector{2, Float64}[]
    prev_point = SVector{2, Float64}(NaN, NaN)

    for new_point in old_line
        if !all(isfinite.(new_point))
            if length(new_line) > 0 && all(isfinite.(new_line[end]))
                push!(new_line, new_point)
            end
        else
            if !all(isfinite.(prev_point))
                if _inside(new_point)
                    push!(new_line, new_point)
                end
            else
                # both prev_point and new_point are finite
                add_overlap!(new_line, prev_point, new_point, sizes)
            end
        end
        prev_point = new_point
    end
    map(p -> SVector{2, Float64}(p[1], p[2]), new_line)
end

function add_overlap!(new_line, prev_point, new_point, sizes)
    _inside(point::SVector{2, Float64}) = abs(point[1]) <= sizes[1] && abs(point[2]) <= sizes[2]

    next_inside = _inside(new_point)
    ndiscover = 2 - _inside(prev_point) - next_inside
    if ndiscover == 0
        push!(new_line, new_point)
        return
    end

    # line is at least partially outside
    direction = new_point - prev_point
    dist_new_sq = sum(d->d*d, direction)
    n = norm(direction)
    normal = SVector{2, Float64}(-direction[2]/n, direction[1]/n)
    constant = normal ⋅ prev_point

    discovered = SVector{2, Float64}[]
    function add_valid!(point::SVector{2, Float64})
        distsq = (point - prev_point) ⋅ direction
        if distsq >= 0 && distsq <= dist_new_sq
            push!(discovered, point)
        end
    end
    x1 = (constant - sizes[2] * normal[2]) / normal[1]
    if abs(x1) <= sizes[1]
        add_valid!(SVector{2, Float64}(x1, sizes[2]))
    end
    x2 = (constant + sizes[2] * normal[2]) / normal[1]
    if abs(x2) <= sizes[1]
        add_valid!(SVector{2, Float64}(x2, -sizes[2]))
    end

    y1 = (constant - sizes[1] * normal[1]) / normal[2]
    if abs(y1) < sizes[2]
        add_valid!(SVector{2, Float64}(sizes[1], y1))
    end
    y2 = (constant + sizes[1] * normal[1]) / normal[2]
    if abs(y2) < sizes[2]
        add_valid!(SVector{2, Float64}(-sizes[1], y2))
    end

    if length(discovered) == 0 && ndiscover == 2
        # line is fully outside of the box
        return
    end
    if length(discovered) != ndiscover
        # bad point at edge; let's just ignore it
        return
    end

    if ndiscover == 2
        if length(new_line) > 0 && all(isfinite.(new_line[end]))
            push!(new_line, SVector{2, Float64}(NaN, NaN))
        end
        if (discovered[1] - prev_point) ⋅ direction > (discovered[2] - prev_point) ⋅ direction
            push!(new_line, discovered[2])
            push!(new_line, discovered[1])
        else
            push!(new_line, discovered[1])
            push!(new_line, discovered[2])
        end
    else
        @assert ndiscover == 1
        if next_inside && length(new_line) > 0 && all(isfinite.(new_line[end]))
            push!(new_line, SVector{2, Float64}(NaN, NaN))
        end
        push!(new_line, discovered[1])
        if next_inside
            push!(new_line, new_point)
        end
    end
end


"""
    SingleSequenceDiagramLine(times, amplitudes, event_times, event_amplitudes)

A single line in a sequence diagram (e.g., RFx, Gy, ADC).
"""
struct SingleSequenceDiagramLine
    times :: Vector{Float64}
    amplitudes :: Vector{Float64}
    event_times :: Vector{Float64}
    event_amplitudes :: Vector{Float64}
end

duration_diagram(pl::SingleSequenceDiagramLine) = max(
    iszero(length(pl.times)) ? 0. : pl.times[end],
    iszero(length(pl.event_times)) ? 0. : pl.event_times[end],
)

SingleSequenceDiagramLine(times::Vector{Float64}, amplitudes::Vector{Float64}) = SingleSequenceDiagramLine(times, amplitudes, Float64[], Float64[])

function SingleSequenceDiagramLine(control_points::AbstractVector{<:Tuple}, duration::Number)
    times = [cp[1] for cp in control_points]
    amplitudes = [cp[2] for cp in control_points]
    if times[1] > 0
        pushfirst!(times, 0.)
        pushfirst!(amplitudes, 0.)
    end
    if times[end] < duration
        push!(times, duration)
        push!(amplitudes, 0.)
    end
    return SingleSequenceDiagramLine(times, amplitudes, Float64[], Float64[])
end

SingleSequenceDiagramLine(duration::Number) = SingleSequenceDiagramLine([0., duration], [0., 0.], Float64[], Float64[])

function normalise(lines::Vector{SingleSequenceDiagramLine})
    max_amp = maximum([maximum(abs.(line.amplitudes), init=0.) for line in lines])
    if iszero(max_amp)
        max_amp = 1.
    end

    max_event_amp = maximum([maximum(abs.(line.event_amplitudes), init=0.) for line in lines])
    if iszero(max_event_amp)
        max_event_amp = 1.
    end
    [SingleSequenceDiagramLine(line.times, line.amplitudes ./ max_amp, line.event_times, line.event_amplitudes ./ max_event_amp) for line in lines]
end

"""
    SequenceDiagram(; RFx, RFy, Gx, Gy, Gz, ADC)

All the lines forming a sequence diagram.

Each parameter should be a [`SinglePlotLine`](@ref) if provided.
Any parameters not provided will be set to a [`SinglePlotLine`](@ref) with zero amplitude.
"""
struct SequenceDiagram
    RFx :: SingleSequenceDiagramLine
    RFy :: SingleSequenceDiagramLine
    Gx :: SingleSequenceDiagramLine
    Gy :: SingleSequenceDiagramLine
    Gz :: SingleSequenceDiagramLine
    ADC :: SingleSequenceDiagramLine
end

function extend(sd::SingleSequenceDiagramLine, duration::Number)
    new_times = copy(sd.times)
    new_amplitudes = copy(sd.amplitudes)
    if length(sd.times) == 0 || sd.times[1] > 0
        pushfirst!(new_times, 0.)
        pushfirst!(new_amplitudes, 0.)
    end
    if new_times[end] < duration
        push!(new_times, duration)
        push!(new_amplitudes, 0.)
    end
    return SingleSequenceDiagramLine(new_times, new_amplitudes, sd.event_times, sd.event_amplitudes)
end

function extend(sd::SequenceDiagram)
    duration = duration_diagram(sd)
    SequenceDiagram(
        extend(sd.RFx, duration),
        extend(sd.RFy, duration),
        extend(sd.Gx, duration),
        extend(sd.Gy, duration),
        extend(sd.Gz, duration),
        extend(sd.ADC, duration),
    )
end

normalise(sd::SequenceDiagram) = SequenceDiagram(
    normalise([sd.RFx, sd.RFy])...,
    normalise([sd.Gx, sd.Gy, sd.Gz])...,
    normalise([sd.ADC])...,
)

function SequenceDiagram(waveform::SequenceWaveform)
    RF_times = Float64[]
    RF_ampl = ComplexF64[]

    for (start, finish, parts) in waveform.rf
        push!(RF_times, start)
        push!(RF_ampl, zero(ComplexF64))
        step_size = (finish - start) / length(parts)
        for (index, part) in enumerate(parts)
            push!(RF_times, start + (index - 0.5) * step_size)
            push!(RF_ampl, part.amplitude * exp(1im * deg2rad(part.phase)))
        end
    end

    instant_pulse_times = [t for (t, event) in waveform.instants if event isa PulseEvent]
    instant_pulse_amplitudes = [event.flip_angle * exp(1im * deg2rad(event.phase)) for (_, event) in waveform.instants if event isa PulseEvent]

    instant_grad_times = [t for (t, event) in waveform.instants if event isa GradientEvent]
    instant_grad_amplitudes = [
        [event.qvec[index] for (_, event) in waveform.instants if event isa GradientEvent]
        for index in 1:3
    ]
    SequenceDiagram(
        SingleSequenceDiagramLine(RF_times, real.(RF_ampl), instant_pulse_times, real.(instant_pulse_amplitudes)),
        SingleSequenceDiagramLine(RF_times, imag.(RF_ampl), instant_pulse_times, imag.(instant_pulse_amplitudes)),
        SingleSequenceDiagramLine(waveform.grads[1]..., instant_grad_times, instant_grad_amplitudes[1]),
        SingleSequenceDiagramLine(waveform.grads[2]..., instant_grad_times, instant_grad_amplitudes[2]),
        SingleSequenceDiagramLine(waveform.grads[3]..., instant_grad_times, instant_grad_amplitudes[3]),
        SingleSequenceDiagramLine(Float64[], Float64[], waveform.samples, [1. for _ in waveform.samples]),
    )
end

SequenceDiagram(diagram::SequenceDiagram) = diagram
SequenceDiagram(sequence) = SequenceDiagram(SequenceWaveform(sequence))

duration_diagram(sd::SequenceDiagram) = maximum([
    duration_diagram(sd.RFx),
    duration_diagram(sd.RFy),
    duration_diagram(sd.Gx),
    duration_diagram(sd.Gy),
    duration_diagram(sd.Gz),
    duration_diagram(sd.ADC),
])


end
